language: android
sudo: false
dist: trusty

android:
  components:
    - tools
    - tools
jdk:
  - oraclejdk8

script:
  - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;29.0.2" "platforms;android-29"
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache